# Generated by Django 4.2.4 on 2023-08-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_yml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='차트 날짜')),
                ('rank', models.IntegerField(verbose_name='노래 순위')),
                ('title', models.CharField(max_length=100, verbose_name='노래 제목')),
                ('artist', models.CharField(max_length=100, verbose_name='가수')),
                ('album_image', models.TextField(max_length=100, verbose_name='앨범 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='JpopChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='차트 날짜')),
                ('rank', models.IntegerField(verbose_name='노래 순위')),
                ('title', models.CharField(max_length=100, verbose_name='노래 제목')),
                ('artist', models.CharField(max_length=100, verbose_name='가수')),
                ('album_image', models.TextField(max_length=100, verbose_name='앨범 이미지')),
            ],
        ),
    ]
